/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package footsoft.view.panels.administrator;

import footsoft.model.core.daos.TipoDeEmpleadoDao;
import footsoft.model.core.entities.Comida;
import footsoft.model.core.entities.TipoDeEmpleado;
import footsoft.model.core.entities.ValorDeComida;
import footsoft.view.models.list.FSComboBoxModelGeneric;
import footsoft.view.models.list.FactoryCellListRenderer;
import footsoft.view.panels.RootPanel;

/**
 *
 * @author Klac
 */
public class PanelConfiCentroCosto extends RootPanel {

    private TipoDeEmpleado centroDeCosto;
    
    public PanelConfiCentroCosto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCentroCostos = createTextField();
        jButtonRelacionarComida = createButtonSecondary();
        jPanelWork = new javax.swing.JPanel();
        jPanelOperationNewUpdate = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonNewCentroCosto = createButtonSecondary();
        jButtonUpdateCentroCosto = createButtonSecondary();
        jButtonTerminar = createButtonSecondary();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jPanel1.setBackground(getBackground());
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), "Centros de Costos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        jList1.setBackground(getBackground());
        jList1.setModel(new FSComboBoxModelGeneric(TipoDeEmpleado.class)
        );
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jList1.setCellRenderer(FactoryCellListRenderer.createListCellRendererRegistrator());
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(getBackground());
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), "Operaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel1.setText("Centro de costos:");
        jLabel1.setVisible(false);

        jTextFieldCentroCostos.setVisible(false);
        jTextFieldCentroCostos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCentroCostosKeyReleased(evt);
            }
        });

        jButtonRelacionarComida.setText("Agregar servicio de comida");
        jButtonRelacionarComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelacionarComidaActionPerformed(evt);
            }
        });
        jButtonRelacionarComida.setVisible(false);

        jPanelWork.setBackground(getBackground());
        jPanelWork.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanelWork.setVisible(false);
        jPanelWork.setLayout(new java.awt.BorderLayout());

        jPanelOperationNewUpdate.setBackground(getBackground());

        jButtonNewCentroCosto.setText("Agregar centro de costo");
        jButtonNewCentroCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewCentroCostoActionPerformed(evt);
            }
        });

        jButtonUpdateCentroCosto.setText("Modificar");

        javax.swing.GroupLayout jPanelOperationNewUpdateLayout = new javax.swing.GroupLayout(jPanelOperationNewUpdate);
        jPanelOperationNewUpdate.setLayout(jPanelOperationNewUpdateLayout);
        jPanelOperationNewUpdateLayout.setHorizontalGroup(
            jPanelOperationNewUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanelOperationNewUpdateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonNewCentroCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonUpdateCentroCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelOperationNewUpdateLayout.setVerticalGroup(
            jPanelOperationNewUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOperationNewUpdateLayout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOperationNewUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonUpdateCentroCosto)
                    .addComponent(jButtonNewCentroCosto))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jButtonTerminar.setText("Terminar");
        jButtonTerminar.setVisible(false);
        jButtonTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTerminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOperationNewUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelWork, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCentroCostos))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonRelacionarComida, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldCentroCostos)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRelacionarComida)
                    .addComponent(jButtonTerminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelWork, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanelOperationNewUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRelacionarComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelacionarComidaActionPerformed
        centroDeCosto.setNombre(jTextFieldCentroCostos.getText());
        jPanelWork.setVisible(true);
        jButtonRelacionarComida.setEnabled(false);
        PanelAddValorFoot panelAddValorFoot = new PanelAddValorFoot(centroDeCosto,jPanelWork,jButtonRelacionarComida);
        panelAddValorFoot.setBotonTerminar(jButtonTerminar);
        changedPanelFoot(panelAddValorFoot);
        
    }//GEN-LAST:event_jButtonRelacionarComidaActionPerformed

    private void jTextFieldCentroCostosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCentroCostosKeyReleased
        jButtonRelacionarComida.setVisible(jTextFieldCentroCostos.getText().compareTo("") != 0);
    }//GEN-LAST:event_jTextFieldCentroCostosKeyReleased

    private void jButtonNewCentroCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewCentroCostoActionPerformed
        showOrHideFormulary(true);
        jPanelOperationNewUpdate.setVisible(false);
        centroDeCosto = new TipoDeEmpleado();
    }//GEN-LAST:event_jButtonNewCentroCostoActionPerformed

    private void jButtonTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTerminarActionPerformed
         if(centroDeCosto == null) return;
         
         try{
             TipoDeEmpleadoDao tipoEmpleDao = new TipoDeEmpleadoDao();
             tipoEmpleDao.addTipoEmpleado(centroDeCosto);
             ((FSComboBoxModelGeneric)jList1.getModel()).addElement(centroDeCosto);
             showOrHideFormulary(false);
             showOHideButtons(false);
             jPanelWork.setVisible(false);
             jPanelOperationNewUpdate.setVisible(true);
             
         }catch(java.sql.SQLException ex){
             ex.printStackTrace();
         }
    }//GEN-LAST:event_jButtonTerminarActionPerformed


    private void changedPanelFoot(javax.swing.JPanel panel){
        jPanelWork.removeAll();
        jPanelWork.setLayout(new java.awt.BorderLayout());
        jPanelWork.add(panel, java.awt.BorderLayout.CENTER);
        jPanelWork.updateUI();
    }
    
    private void showOHideButtons(boolean show){
        jButtonRelacionarComida.setVisible(show);
        jButtonTerminar.setVisible(show);
    }
    
    private void showOrHideFormulary(boolean show){
        jLabel1.setVisible(show);
        jTextFieldCentroCostos.setVisible(show);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNewCentroCosto;
    private javax.swing.JButton jButtonRelacionarComida;
    private javax.swing.JButton jButtonTerminar;
    private javax.swing.JButton jButtonUpdateCentroCosto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelOperationNewUpdate;
    private javax.swing.JPanel jPanelWork;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldCentroCostos;
    // End of variables declaration//GEN-END:variables
}
