/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package footsoft.view.dialogs.administrator;

import footsoft.view.dialogs.MainDialog;
import footsoft.view.panels.administrator.PanelConfiBolsaEmpleo;
import footsoft.view.panels.administrator.PanelConfiComida;
import footsoft.view.panels.administrator.PanelConfiCentroCosto;

/**
 *
 * @author Klac
 */
public class DialogConfigurationBolsaAndCentro extends MainDialog {

    /**
     * Creates new form DialogConfigurationBolsaAndCentro
     */
    public DialogConfigurationBolsaAndCentro() {
        super();
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneConfi = new javax.swing.JTabbedPane();
        panelCentroCosto = new javax.swing.JPanel();
        panelComida = new javax.swing.JPanel();
        panelBolsaEmpleo = new javax.swing.JPanel();
        panelSut = new javax.swing.JPanel();
        jButton1 = createButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        setForeground(new java.awt.Color(102, 102, 102));

        jTabbedPaneConfi.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPaneConfi.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jTabbedPaneConfi.setForeground(getForeground());
        jTabbedPaneConfi.setFont(getFont());

        panelCentroCosto.setLayout(new java.awt.BorderLayout());
        panelCentroCosto.add(new PanelConfiCentroCosto(),java.awt.BorderLayout.CENTER);
        jTabbedPaneConfi.addTab("Centros de Costos", panelCentroCosto);

        panelComida.setLayout(new java.awt.BorderLayout());
        panelComida.add(new PanelConfiComida(),java.awt.BorderLayout.CENTER);
        jTabbedPaneConfi.addTab("Comidas", panelComida);

        panelBolsaEmpleo.setLayout(new java.awt.BorderLayout());

        panelBolsaEmpleo.add(new PanelConfiBolsaEmpleo(),java.awt.BorderLayout.CENTER);

        jTabbedPaneConfi.addTab("Bolsas de Empleo", panelBolsaEmpleo);

        getContentPane().add(jTabbedPaneConfi, java.awt.BorderLayout.CENTER);

        panelSut.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSutLayout = new javax.swing.GroupLayout(panelSut);
        panelSut.setLayout(panelSutLayout);
        panelSutLayout.setHorizontalGroup(
            panelSutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSutLayout.createSequentialGroup()
                .addContainerGap(740, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelSutLayout.setVerticalGroup(
            panelSutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap())
        );

        getContentPane().add(panelSut, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        doClose();
    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTabbedPane jTabbedPaneConfi;
    private javax.swing.JPanel panelBolsaEmpleo;
    private javax.swing.JPanel panelCentroCosto;
    private javax.swing.JPanel panelComida;
    private javax.swing.JPanel panelSut;
    // End of variables declaration//GEN-END:variables
}
