-- MySQL Script generated by MySQL Workbench
-- 08/18/15 15:20:04
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema FootSoft
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FootSoft` DEFAULT CHARACTER SET latin1 COLLATE latin1_spanish_ci ;
USE `FootSoft` ;

-- -----------------------------------------------------
-- Table `FootSoft`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FootSoft`.`User` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `password` TEXT NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FootSoft`.`Tipo_de_Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FootSoft`.`Tipo_de_Empleado` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `tipo_de_empleado` TEXT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FootSoft`.`Comida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FootSoft`.`Comida` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nombre_de_comida` TEXT NOT NULL,
  `valor` DOUBLE NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FootSoft`.`Valor_de_Comida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FootSoft`.`Valor_de_Comida` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `descuento` DOUBLE NOT NULL,
  `subsidio` DOUBLE NOT NULL,
  `Tipo_de_Empleado_codigo` INT NOT NULL,
  `Comida_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_Valor_de_Comida_Tipo_de_Empleado1_idx` (`Tipo_de_Empleado_codigo` ASC),
  INDEX `fk_Valor_de_Comida_Comida1_idx` (`Comida_codigo` ASC),
  CONSTRAINT `fk_Valor_de_Comida_Tipo_de_Empleado1`
    FOREIGN KEY (`Tipo_de_Empleado_codigo`)
    REFERENCES `FootSoft`.`Tipo_de_Empleado` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Valor_de_Comida_Comida1`
    FOREIGN KEY (`Comida_codigo`)
    REFERENCES `FootSoft`.`Comida` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FootSoft`.`Fechas_de_Corte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FootSoft`.`Fechas_de_Corte` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `fecha_de_inicio` DATE NOT NULL,
  `fecha_de_cierre` DATE NOT NULL,
  `predominar` BIT NOT NULL,
  PRIMARY KEY (`codigo`, `predominar`, `fecha_de_inicio`, `fecha_de_cierre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FootSoft`.`Bolsa_de_Empleo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FootSoft`.`Bolsa_de_Empleo` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `bolsa_de_Empleo` TEXT NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FootSoft`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FootSoft`.`Empleado` (
  `cedula` INT NOT NULL,
  `nombres` TEXT NOT NULL,
  `Tipo_de_Empleado_codigo` INT NOT NULL,
  `Bolsa_de_Empleo_codigo` INT NOT NULL,
  PRIMARY KEY (`cedula`),
  INDEX `fk_Empleado_Tipo_de_Empleado1_idx` (`Tipo_de_Empleado_codigo` ASC),
  INDEX `fk_Empleado_Bolsa_de_Empleo1_idx` (`Bolsa_de_Empleo_codigo` ASC),
  CONSTRAINT `fk_Empleado_Tipo_de_Empleado1`
    FOREIGN KEY (`Tipo_de_Empleado_codigo`)
    REFERENCES `FootSoft`.`Tipo_de_Empleado` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_Bolsa_de_Empleo1`
    FOREIGN KEY (`Bolsa_de_Empleo_codigo`)
    REFERENCES `FootSoft`.`Bolsa_de_Empleo` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FootSoft`.`Contabilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FootSoft`.`Contabilidad` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `Comida_codigo` INT NOT NULL,
  `Empleado_cedula` INT NOT NULL,
  INDEX `fk_Contabilidad_Comida1_idx` (`Comida_codigo` ASC),
  INDEX `fk_Contabilidad_Empleado1_idx` (`Empleado_cedula` ASC),
  PRIMARY KEY (`codigo`),
  CONSTRAINT `fk_Contabilidad_Comida1`
    FOREIGN KEY (`Comida_codigo`)
    REFERENCES `FootSoft`.`Comida` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contabilidad_Empleado1`
    FOREIGN KEY (`Empleado_cedula`)
    REFERENCES `FootSoft`.`Empleado` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FootSoft`.`Consumo_de_Comida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FootSoft`.`Consumo_de_Comida` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `fecha_de_consumo` TIMESTAMP NULL,
  `Contabilidad_codigo1` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_Consumo_de_Comida_Contabilidad1_idx` (`Contabilidad_codigo1` ASC),
  CONSTRAINT `fk_Consumo_de_Comida_Contabilidad1`
    FOREIGN KEY (`Contabilidad_codigo1`)
    REFERENCES `FootSoft`.`Contabilidad` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `FootSoft`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `FootSoft`;
INSERT INTO `FootSoft`.`User` (`codigo`, `password`) VALUES (1, '12345');
INSERT INTO `FootSoft`.`User` (`codigo`, `password`) VALUES (2, '1234');

COMMIT;

